name: flutter_link_previewer
description: >
  Customizable link and URL preview extracted from the
  provided text with the ability to render from the cache.
version: 3.1.1
homepage: https://flyer.chat
repository: https://github.com/flyerhq/flutter_link_previewer

screenshots:
 - description: 'Customizable link and URL preview extracted from the'
   path: screenshots/screenshot.png

environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: '>=2.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_chat_types: ^3.6.1
  flutter_linkify: ^6.0.0
  html: ^0.15.4
  http: ^1.0.0
  linkify: ^5.0.0
  meta: ^1.9.1
  url_launcher: ^6.1.11

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
